name: main
on: [push, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@main
    - name: Sync to-do comments to GitHub Issues
      uses: tomashubelbauer/github-actions-code-to-do-github-issues-backup@main
